### PR TITLE
Bootstrap Existing Plugins

### PR DESCRIPTION
**Pull request by original-brownbear**
Merges histories of existing plugins into this repo

### CODE REVIEW

**Comment by karmi** [comment]
Hi @original-brownbear, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-integration-elasticsearch/pull/3.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by andrewvc** [comment]
I'm +1 on this. 

One question, can we incrementally re-run this? How can we make sure that we don't lose history here?

Alternatively, we can send out a notice to all LS devs not to merge code into any other ES plugins until we're done here.

**Comment by original-brownbear** [comment]
@andrewvc yea we can pull in new commits from the other repos (It's a bit of a pain to do it, but should work just fine :))

**Comment by andrewvc** [comment]
I'm OK then merging this as-is if it's helpful, but we're really blocked here until the docs changes come in.

**Comment by original-brownbear** [comment]
@andrewvc alrighty merging then. Will add a PR for the rest of the infrastructure created for this while we look into the docs thing :)

**Pull request merged**
